kind: Deployment
apiVersion: apps/v1
metadata:
  name: kcp-syncer
  namespace: {{ .WorkSpace }}
  labels:
    app: kcp-syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcp-syncer
  template:
    metadata:
      labels:
        app: kcp-syncer
    spec:
      serviceAccountName: kcp-sa
      containers:
      - name: syncer
        image: {{ .Image }}
        args:
          - "/syncer"
          - "--cluster={{ .Cluster }}"
          - "--from_kubeconfig=/syncer-kubeconfig/kubeconfig"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        volumeMounts:
        - name: syncer-kubeconfig-secret
          mountPath: "/syncer-kubeconfig"
          readOnly: true
      volumes:
      - name: syncer-kubeconfig-secret
        secret:
          secretName: syncer-kubeconfig-secret
